name: CI Test Build

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [14.x, 16.x, lts/*, latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup Node.js (version: ${{ matrix.node-version }})'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci --prefer-offline --ignore-scripts

      - name: Rebuild and prepare depencencies
        continue-on-error: true #TODO: we currently continue as a warning!
        # `npm rebuild` will run all those post-install scripts for us.
        run: |
          if npm rebuild && npm run prepare --if-present ; then
          # ensure it is a warning, rather than an error, as GH workflow does not support it!
            echo '### :warning: issues encountered with `npm rebuild && npm run prepare`' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run License check
        continue-on-error: true #TODO: we currently continue as a warning!
        # check that all dependencies are .NET nanoFramework OSS license compatible
        run: |
          npm run check-package-licence-compatible --if-present

      - name: Run outdated package check
        continue-on-error: true #TODO: we currently continue as a warning!
        run: |
          if npm run check-package-outdated --if-present ; then
          # ensure it is a warning, rather than an error, as GH workflow does not support it!
            echo '### :warning: Outdated packages detected!, check `npm run check-package-outdated`' >> $GITHUB_STEP_SUMMARY
            exit 0 #TODO: we currently just ignore this error and raise it as a warning!
          fi

      - name: Run audit package check
        continue-on-error: true #TODO: we currently continue as a warning!
        run: |
          if npm audit --dry-run --if-present ; then
          # ensure it is a warning, rather than an error, as GH workflow does not support it!
            echo '### :warning: Package audit check failed!, check `npm audit`' >> $GITHUB_STEP_SUMMARY
            exit 0 #TODO: we currently just ignore this error and raise it as a warning!
          fi

      - name: Run lint checks
        run: |
          npm run lint --if-present

      - name: Run build
        run: |
          npm run build --if-present

      - name: Run smoke tests for VSCode extension
        continue-on-error: true # TODO: remove once improved!
        run: |
          # enable the display for XWindows
          # export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
          export DISPLAY=:99.0
          npm run test --if-present

#       - name: Run Sonar Scan
#         continue-on-error: true # TODO: should handle better!
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /home/runner/.npm/_logs/**/* # TODO: the path should be an environment variable!
